# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v2
      
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'


      - name: Verify Formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Install Pub Dependencies
        run: flutter pub get

      - name: Analyze Project Source
        run: dart analyze

      - name: Run unit tests
        run: /bin/bash  /home/runner/work/pylons_dart_sdk/pylons_dart_sdk/script/test_coverage.sh
      
